# Generated by Django 5.2.6 on 2025-10-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='descripcion',
            new_name='direccion',
        ),
    ]
